{extends file="./base.tpl"}
{block name="content"}
<h2 class="txt-">Galeria de Imagenes</h2>
<article class="igp-gallery" >
  <div class="field-item"><a href="http://ovs.igp.gob.pe/sites/ovs.igp.gob.pe/files/pictures/TrabajodeCampo/Ticsani/2015/Marzo19-20/ticsani_estaciones_04.jpg" title="Marzo 19-20, 2015" class="colorbox init-colorbox-processed cboxElement" rel="gallery-node-128-field_imagen_gallery"><img typeof="foaf:Image" src="http://ovs.igp.gob.pe/sites/ovs.igp.gob.pe/files/styles/gallery_small_colobox/public/pictures/TrabajodeCampo/Ticsani/2015/Marzo19-20/ticsani_estaciones_04.jpg?itok=Jow7Ke1t" width="185" height="160" alt="" title="Marzo 19-20, 2015"></a>  <span class="title">Marzo 19-20, 2015</span>
  </div>
  <div class="field-item"><a href="http://ovs.igp.gob.pe/sites/ovs.igp.gob.pe/files/pictures/TrabajodeCampo/Ticsani/Mayo/Mayo15-20/Tic%20May%2015-20%2019.jpg" title="Mayo 15-20, 2014" class="colorbox init-colorbox-processed cboxElement" rel="gallery-node-128-field_imagen_gallery"><img typeof="foaf:Image" src="http://ovs.igp.gob.pe/sites/ovs.igp.gob.pe/files/styles/gallery_small_colobox/public/pictures/TrabajodeCampo/Ticsani/Mayo/Mayo15-20/Tic%20May%2015-20%2019.jpg?itok=JS6oagMw" width="185" height="160" alt="" title="Mayo 15-20, 2014"></a>  <span class="title">Mayo 15-20, 2014</span>
  </div>
  <div class="field-item"><a href="http://ovs.igp.gob.pe/sites/ovs.igp.gob.pe/files/pictures/TrabajodeCampo/Ticsani/Mayo/Mayo15-20/Tic%20May%2015-20%2018.jpg" title="Mayo 15-20, 2014" class="colorbox init-colorbox-processed cboxElement" rel="gallery-node-128-field_imagen_gallery"><img typeof="foaf:Image" src="http://ovs.igp.gob.pe/sites/ovs.igp.gob.pe/files/styles/gallery_small_colobox/public/pictures/TrabajodeCampo/Ticsani/Mayo/Mayo15-20/Tic%20May%2015-20%2018.jpg?itok=iulju8re" width="185" height="160" alt="" title="Mayo 15-20, 2014"></a>  <span class="title">Mayo 15-20, 2014</span>
  </div>
  <div class="field-item"><a href="http://ovs.igp.gob.pe/sites/ovs.igp.gob.pe/files/pictures/TrabajodeCampo/Ticsani/Mayo/Mayo15-20/Tic%20May%2015-20%2017.jpg" title="Mayo 15-20, 2014" class="colorbox init-colorbox-processed cboxElement" rel="gallery-node-128-field_imagen_gallery"><img typeof="foaf:Image" src="http://ovs.igp.gob.pe/sites/ovs.igp.gob.pe/files/styles/gallery_small_colobox/public/pictures/TrabajodeCampo/Ticsani/Mayo/Mayo15-20/Tic%20May%2015-20%2017.jpg?itok=b2Eu6Dk_" width="185" height="160" alt="" title="Mayo 15-20, 2014"></a>  <span class="title">Mayo 15-20, 2014</span>
  </div>
  <div class="field-item"><a href="http://ovs.igp.gob.pe/sites/ovs.igp.gob.pe/files/pictures/TrabajodeCampo/Ticsani/Mayo/Mayo15-20/Tic%20May%2015-20%2016.jpg" title="Mayo 15-20, 2014" class="colorbox init-colorbox-processed cboxElement" rel="gallery-node-128-field_imagen_gallery"><img typeof="foaf:Image" src="http://ovs.igp.gob.pe/sites/ovs.igp.gob.pe/files/styles/gallery_small_colobox/public/pictures/TrabajodeCampo/Ticsani/Mayo/Mayo15-20/Tic%20May%2015-20%2016.jpg?itok=1T0Jod7V" width="185" height="160" alt="" title="Mayo 15-20, 2014"></a>  <span class="title">Mayo 15-20, 2014</span>
  </div>
  <div class="field-item"><a href="http://ovs.igp.gob.pe/sites/ovs.igp.gob.pe/files/pictures/TrabajodeCampo/Ticsani/Mayo/Mayo15-20/Tic%20May%2015-20%2015.jpg" title="Mayo 15-20, 2014" class="colorbox init-colorbox-processed cboxElement" rel="gallery-node-128-field_imagen_gallery"><img typeof="foaf:Image" src="http://ovs.igp.gob.pe/sites/ovs.igp.gob.pe/files/styles/gallery_small_colobox/public/pictures/TrabajodeCampo/Ticsani/Mayo/Mayo15-20/Tic%20May%2015-20%2015.jpg?itok=-IXKlIFV" width="185" height="160" alt="" title="Mayo 15-20, 2014"></a>  <span class="title">Mayo 15-20, 2014</span>
  </div>
  <div class="field-item"><a href="http://ovs.igp.gob.pe/sites/ovs.igp.gob.pe/files/pictures/TrabajodeCampo/Ticsani/Mayo/Mayo15-20/Tic%20May%2015-20%2014.jpg" title="Mayo 15-20, 2014" class="colorbox init-colorbox-processed cboxElement" rel="gallery-node-128-field_imagen_gallery"><img typeof="foaf:Image" src="http://ovs.igp.gob.pe/sites/ovs.igp.gob.pe/files/styles/gallery_small_colobox/public/pictures/TrabajodeCampo/Ticsani/Mayo/Mayo15-20/Tic%20May%2015-20%2014.jpg?itok=qoGjGp1F" width="185" height="160" alt="" title="Mayo 15-20, 2014"></a>  <span class="title">Mayo 15-20, 2014</span>
  </div>
  <div class="field-item"><a href="http://ovs.igp.gob.pe/sites/ovs.igp.gob.pe/files/pictures/TrabajodeCampo/Ticsani/Mayo/Mayo15-20/Tic%20May%2015-20%2013.jpg" title="Mayo 15-20, 2014" class="colorbox init-colorbox-processed cboxElement" rel="gallery-node-128-field_imagen_gallery"><img typeof="foaf:Image" src="http://ovs.igp.gob.pe/sites/ovs.igp.gob.pe/files/styles/gallery_small_colobox/public/pictures/TrabajodeCampo/Ticsani/Mayo/Mayo15-20/Tic%20May%2015-20%2013.jpg?itok=wq-DPQgq" width="185" height="160" alt="" title="Mayo 15-20, 2014"></a>  <span class="title">Mayo 15-20, 2014</span>
  </div>
  <div class="field-item"><a href="http://ovs.igp.gob.pe/sites/ovs.igp.gob.pe/files/pictures/TrabajodeCampo/Ticsani/Mayo/Mayo15-20/Tic%20May%2015-20%2012.jpg" title="Mayo 15-20, 2014" class="colorbox init-colorbox-processed cboxElement" rel="gallery-node-128-field_imagen_gallery"><img typeof="foaf:Image" src="http://ovs.igp.gob.pe/sites/ovs.igp.gob.pe/files/styles/gallery_small_colobox/public/pictures/TrabajodeCampo/Ticsani/Mayo/Mayo15-20/Tic%20May%2015-20%2012.jpg?itok=fZS4p3Ik" width="185" height="160" alt="" title="Mayo 15-20, 2014"></a>  <span class="title">Mayo 15-20, 2014</span>
  </div>
  <div class="field-item"><a href="http://ovs.igp.gob.pe/sites/ovs.igp.gob.pe/files/pictures/TrabajodeCampo/Ticsani/Mayo/Mayo15-20/Tic%20May%2015-20%2011.jpg" title="Mayo 15-20, 2014" class="colorbox init-colorbox-processed cboxElement" rel="gallery-node-128-field_imagen_gallery"><img typeof="foaf:Image" src="http://ovs.igp.gob.pe/sites/ovs.igp.gob.pe/files/styles/gallery_small_colobox/public/pictures/TrabajodeCampo/Ticsani/Mayo/Mayo15-20/Tic%20May%2015-20%2011.jpg?itok=76JnKIlC" width="185" height="160" alt="" title="Mayo 15-20, 2014"></a>  <span class="title">Mayo 15-20, 2014</span>   </div>
  <div class="field-item"><a href="http://ovs.igp.gob.pe/sites/ovs.igp.gob.pe/files/pictures/TrabajodeCampo/Ticsani/Mayo/Mayo15-20/Tic%20May%2015-20%2010.jpg" title="Mayo 15-20, 2014" class="colorbox init-colorbox-processed cboxElement" rel="gallery-node-128-field_imagen_gallery"><img typeof="foaf:Image" src="http://ovs.igp.gob.pe/sites/ovs.igp.gob.pe/files/styles/gallery_small_colobox/public/pictures/TrabajodeCampo/Ticsani/Mayo/Mayo15-20/Tic%20May%2015-20%2010.jpg?itok=Lq2Eqcb9" width="185" height="160" alt="" title="Mayo 15-20, 2014"></a>  <span class="title">Mayo 15-20, 2014</span>
  </div>
  <div class="field-item"><a href="http://ovs.igp.gob.pe/sites/ovs.igp.gob.pe/files/pictures/TrabajodeCampo/Ticsani/Mayo/Mayo15-20/Tic%20May%2015-20%209.jpg" title="Mayo 15-20, 2014" class="colorbox init-colorbox-processed cboxElement" rel="gallery-node-128-field_imagen_gallery"><img typeof="foaf:Image" src="http://ovs.igp.gob.pe/sites/ovs.igp.gob.pe/files/styles/gallery_small_colobox/public/pictures/TrabajodeCampo/Ticsani/Mayo/Mayo15-20/Tic%20May%2015-20%209.jpg?itok=580cU3IT" width="185" height="160" alt="" title="Mayo 15-20, 2014"></a>  <span class="title">Mayo 15-20, 2014</span>
  </div>
  <div class="field-item"><a href="http://ovs.igp.gob.pe/sites/ovs.igp.gob.pe/files/pictures/TrabajodeCampo/Ticsani/Mayo/Mayo15-20/Tic%20May%2015-20.jpg" title="Mayo 15-20, 2014" class="colorbox init-colorbox-processed cboxElement" rel="gallery-node-128-field_imagen_gallery"><img typeof="foaf:Image" src="http://ovs.igp.gob.pe/sites/ovs.igp.gob.pe/files/styles/gallery_small_colobox/public/pictures/TrabajodeCampo/Ticsani/Mayo/Mayo15-20/Tic%20May%2015-20.jpg?itok=YSrheqbK" width="185" height="160" alt="" title="Mayo 15-20, 2014"></a>  <span class="title">Mayo 15-20, 2014</span>
  </div>
  <div class="field-item"><a href="http://ovs.igp.gob.pe/sites/ovs.igp.gob.pe/files/pictures/TrabajodeCampo/Ticsani/ticsani.jpg" title="Volcán Ticsani - Moquegua" class="colorbox init-colorbox-processed cboxElement" rel="gallery-node-128-field_imagen_gallery"><img typeof="foaf:Image" src="http://ovs.igp.gob.pe/sites/ovs.igp.gob.pe/files/styles/gallery_small_colobox/public/pictures/TrabajodeCampo/Ticsani/ticsani.jpg?itok=tiAS_bz8" width="185" height="160" alt="" title="Volcán Ticsani - Moquegua"></a>  <span class="title">Volcán Ticsani - Moquegua</span>
  </div>
</article>

<pre class="prettyprint linenums">
    <ol class="linenums">
    <li><span class="tag">&lt;article</span> <span class="atn">class</span><span class="pun">=</span><span class="atv">"igp-gallery"</span><span class="tag">&gt;</span></li>
    <li><span class="pln">  </span><span class="tag">&lt;div</span> <span class="atn">class</span><span class="pun">=</span><span class="atv">"field-item"</span><span class="tag">&gt;</span></li>
    <li ><span class="pln">  </span><span class="pln">  </span><span class="tag">&lt;a</span> <span class="atn">href</span><span class="pun">=</span><span class="atv">"..."</span><span class="atn">class</span><span class="pun">=</span><span class="atv">"colorbox"</span> <span class="tag">&gt;</span></li>
    <li><span class="pln">  </span><span class="pln">  </span><span class="pln">  </span><span class="tag">&lt;img</span> <span class="atn">src</span><span class="pun">=</span><span class="atv">"..."</span><span class="tag">&gt;</span></li>
    <li><span class="pln">  </span><span class="pln">  </span><span class="tag">&lt;/a&gt;</span></li>
    <li><span class="pln">  </span><span class="tag">&lt;/div&gt;</span></li>
    <li><span class="pln">  ...</span></li>
    <li><span class="tag">&lt;/article&gt;</span></li>
    </ol>
</pre>
{/block}
